export const LOADING = "Loading..."
export const PAGE = "Page"
export const PREV = "Prev"
export const NEXT = "Next"
export const FAVORITE_TITLE = "Your Favorite Pokémon"
export const NO_FAVORITE_MESSAGE = "No favorites added yet."
export const HOME = "Home"
export const SEARCH = "Search"
export const SELECT = "Select"
export const POKEMON_FINDER = "Pokémon Finder"
export const VIEW_FAVORITES = "View Favorites"
export const FAVORITE = "Favorite"
export const MARK = "Mark"
export const NAME = "Name"
export const TYPE = "Type"
export const STATS = "Stats"
export const ABILITIES = "Abilities"
export const SOME_MOVES = "Some Moves"
export const DETAILS = "Details"


